language: python

dist: xenial

jobs:
  include:
    - stage: "Unit test"
      python: 
        - '3.6'
        - '3.7'
        - '3.8'
      script: coverage run -m unittest discover
    - stage: "Code analyze"
      python: 3.8
      addons:
        sonarcloud:
          organization: "brobots-corporation"
      before_script:
        - coverage run -m unittest discover
        - coverage xml -o coverage-reports/coverage.xml
      script: sonar-scanner

notifications:
  email:
    on_failure: change
    on_error: change