dist: xenial
language: python
git:
  depth: false  # "Shallow clone detected during the analysis"

jobs:
  include:
    - name: "Unit test python 3.6"
      python: 3.6
      install: echo "pass install"
      script: python -m unittest
    - name: "Unit test python 3.7"
      python: 3.7
      install: echo "pass install"
      script: python -m unittest
    - name: "Unit test python 3.8"
      python: 3.8
      install: echo "pass install"
      script: python -m unittest
    - stage: "Code analyze"
      python: 3.8
      addons:
        sonarcloud:
          organization: "brobots-corporation"
      before_script:
        - coverage run --source=bsl2sq -m xmlrunner --output-file=tests.xml
        - coverage xml -o coverage.xml
      script: sonar-scanner
    - stage: "deploy pypi"
      script: skip
      deploy:
        provider: pypi
        user: "__token__"
        password: $PYPI_TOKEN
        distributions: "sdist bdist_wheel"
      on:
        tags: true

notifications:
  email:
    on_failure: change
    on_error: change