dist: xenial
language: python
git:
  depth: false  # "Shallow clone detected during the analysis"

jobs:
  include:
    - name: "Unit test python 3.6"
      python: 3.6
      script: coverage run -m unittest discover
    - name: "Unit test python 3.7"
      python: 3.7
      script: coverage run -m unittest discover
    - name: "Unit test python 3.8"
      python: 3.8
      script: coverage run -m unittest discover
    - stage: "Code analyze"
      python: 3.8
      addons:
        sonarcloud:
          organization: "brobots-corporation"
      before_script:
        - coverage run -m unittest discover
        - coverage xml -o coverage-reports/coverage-unittest.xml
      script: sonar-scanner

notifications:
  email:
    on_failure: change
    on_error: change