language: python

dist: xenial

python:
  - '3.6'
  - '3.7'
  - '3.8'

script: python -m unittest

jobs:
  include:
    - stage: "Code analyze"
      python: 3.8
      addons:
        sonarcloud:
          organization: "brobots-corporation"
      before_script: echo "Пропуск разворачивания тестовой структуру"
      script: sonar-scanner

notifications:
  email:
    on_failure: change
    on_error: change